version: "3.1"

services:
  db:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    restart: "no"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
